#!/usr/bin/perl

use File::Find;
use Tie::File;
use Fcntl;

$numargs=$#ARGV + 1;

print "A total of $numargs arguments.\n";

sub usage {
    die "Usage: update_headers <old-header-file> <new-header-file> <source-extensions>\n";
}

sub readin {
    $str = "";
    open(FH, "<", $_[0]) or die "Can't tie to $_[0]: $!\n";
    while (defined ($line = <FH>)) {
	print "$line";
	$str = "$str$line";
    }
    close FH;
    
    return $str;
}

if ($numargs != 3) {
  usage;
}

$oldheader=$ARGV[0];
$newheader=$ARGV[1];
$extension=$ARGV[2];

print "Changing:\n";
$oldh = readin($oldheader);
print "to:\n";
$newh = readin($newheader);


$srcdir="../src/main/";
$i=0;
my $srcfile;

find(\&processfile, $srcdir);

sub processfile {
    if ($_ =~ m/.*\.$extension$/) {
	$dir = $File::Find::dir;
	printf("(%d)\tNow processing file => %s/%s\n", ++$i, $dir, $_);
	
	$contents = readin($_);
	
	$contents =~ s/\Q$oldh/$newh/smg;
	
	open OUTFILE, ">", $_ or die "Could not open file. $!";
	print OUTFILE ($contents);
	close OUTFILE;
	
	print "$string\n";
    }
}




